# Generated by Django 2.2 on 2022-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motherhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanny',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='rate',
            field=models.IntegerField(default=400),
        ),
    ]
