# Generated by Django 2.2 on 2022-03-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motherhood', '0003_remove_nanny_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.AlterField(
            model_name='nanny',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motherhood.Location'),
        ),
    ]
