# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-24 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motherhood', '0004_auto_20220323_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanny',
            name='image',
            field=models.ImageField(default='./static/images/img_10_sq', upload_to='images/'),
        ),
    ]
