# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-31 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motherhood', '0005_nanny_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=400)),
            ],
            options={
                'ordering': ['rate'],
            },
        ),
        migrations.AddField(
            model_name='nanny',
            name='min_hours',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motherhood.Rate'),
        ),
    ]
