# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-31 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motherhood', '0006_auto_20220331_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
