# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motherhood', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='total_cost',
            field=models.IntegerField(default=1600),
        ),
    ]
